version: '3'

services:
  nest001mysql:
    image: mysql:latest
    container_name: nest001mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql